version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    resources:
      requests:
        cpu: "1.9"
        memory: "8Gi"

  frontend:
    image: node:latest
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start