# File: .github/workflows/workflow.yml
on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@master
    
    - name: "Create random directory"
      run: |
        echo "Starting the creation of a random file"
        cd ~
        mkdir .test_kube
        touch .test_kube/somefile.txt
        echo "some text" > .test_kube/somefile.txt
        echo "Finished creating random file"
    
    - uses: okteto/context@latest
      with:
        url: https://okteto.jona.okteto.me/
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Check kubeconfig file"
      run: cd ~ && ls -al
